title: Full Time Travellers
description: Travel blog - ES / DE
url: "https://gmoraleda.github.io"
baseurl: "/fulltimetravellers"
theme: minima

sass:
  quiet_deps: true
  silenceDeprecations:
    - import
    - global-builtin
    - color-functions

include:
  - _pages

header_pages:
  - es/index.md
  - de/index.md

defaults:
  - scope:
      path: "_posts/es"
    values:
      layout: post
      lang: es
  - scope:
      path: "_posts/de"
    values:
      layout: post
      lang: de
  - scope:
      path: "_pages"
    values:
      layout: page

permalink: /:categories/:year/:month/:day/:title/
