title: Full Time Travellers
description: Travel blog archive - ES / DE
url: "https://gmoraleda.github.io"
baseurl: "/fulltimetravellers"

include:
  - _pages

defaults:
  - scope:
      path: "_posts/es"
    values:
      layout: post
      lang: es
  - scope:
      path: "_posts/de"
    values:
      layout: post
      lang: de
  - scope:
      path: "_pages"
    values:
      layout: page

permalink: /:categories/:year/:month/:day/:title/
